### ISSUE TITLE
Scale x4

### ISSUE THREAD

**Issue by Moaazallaham** [memad73/DualSR#1]
Thank you for sharing your work.

May I ask how what changes are to be done in case I want to upscale with a factor of 4? (if possible)

Thanks in advance.

**Comment by memad73** [comment]
Hi, thanks for your question.

If you want to upsample with a factor of 4, you need to make some small changes to the upsampler and downsampler architectures. For the upsampler, the bilinear interpolation at the beginning of the network should upsample the image by a factor of 4. For the downsampler, you need to change the stride of downsampling to 4. You may need to make more changes in the code because the size of images will be different.

**Comment by Moaazallaham** [comment]
What about the downsampler scale_factor in the options.py?
self.parser.add_argument('--scale_factor_downsampler', type=float, default=0.5, help='scale factor for downsampler')

Should I not also change it to 0.25?

**Comment by Moaazallaham** [comment]
Thanks for your reply.

What about the downsampler scale_factor in the options.py?
self.parser.add_argument('--scale_factor_downsampler', type=float, default=0.5, help='scale factor for downsampler')

Should I not also change it to 0.25?

**Comment by memad73** [comment]
Yes, you need to change scale_factor_downsampler to 0.25. 

If you want some quick results for 4x SR, you can also run original DualSR on LR image and then run it again on the upsampled image. You can consider this solution as the baseline.

**Comment by Moaazallaham** [comment]
I thought of running it twice as you just said, but I was afraid of being unfair when doing the comparison to other works.
But, I will try doing that first and see how it goes.

Thanks for the reply anyway. (I will leave the issue open so I can get back and ask you if you dont mind :))
